backend:
  name: git-gateway
  branch: main
media_folder: '/public/uploads'
public_folder: '/uploads'
locale: 'de'
collections:
  - name: 'post'
    label: 'Posts'
    label_singular: 'Post'
    folder: '/src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'Anonymous' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'About section'
    file: '/src/content/about.md'
    fields:
      - { label: 'Headline', name: 'headline', widget: 'string' }
      - { label: 'Text', name: 'text', widget: 'markdown' }
